export const users = [
  {
    id: "1",
    username: "Nikos",
    password: "password",
    role: "user",
    id_licence: "AM 154568",
    one_time_password: "A25A25",
  },
  {
    id: "2",
    username: "Stathis",
    password: "password",
    role: "user",
    id_licence: "AH 365495",
    one_time_password: "B25B25",
  },
  {
    id: "3",
    username: "Stavros",
    password: "password",
    role: "user",
    id_licence: "AK 632145",
    one_time_password: "C25C25",
  },
  {
    id: "4",
    username: "DoctorNikos",
    password: "password",
    role: "health",
    id_licence: "AL 545132",
    office_id: "000001",
    personal_id: "000001",
    one_time_password: "D25D25",
  },
  {
    id: "5",
    username: "OfficerStathis",
    password: "password",
    role: "verifier",
    id_licence: "AZ 232563",
    office_id: "000002",
    personal_id: "000002",
    one_time_password: "E25E25",
  },
  {
    id: "6",
    username: "AdminStavrakas",
    password: "password",
    role: "admin",
    id_licence: "AN 154652",
    office_id: "000003",
    personal_id: "000003",
    one_time_password: "F25F25",
  },
];
